#!/usr/bin/env ruby

# enable local usage from cloned repo
root = File.expand_path('../..', __FILE__)
$LOAD_PATH << "#{root}/lib" if File.exist?("#{root}/Gemfile")

require 'roka'

ARGV.each do |text|
  next unless text
  puts '--- %s' % [text]
  puts Roka.convert(text)
end
